name = "depthlume-preview"
compatibility_date = "2026-08-06"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "depthlume-website"
database_id = "a63b5e37-3f11-4206-94a8-4c6eafaab983"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "RELEASES"
bucket_name = "depthlume-private-releases"

[vars]
APP_ENV = "production"
APP_URL = "https://depthlume-preview.pages.dev"
BETA_LIMIT = "10"
