import type { Locale, PublicPage } from './locales';

type PageCopy = { title: string; description: string; heading: string; lede: string; notice: string; body: string };
type Five<T> = [T,T,T,T,T];
type Nine<T> = [T,T,T,T,T,T,T,T,T];
type Twelve<T> = [T,T,T,T,T,T,T,T,T,T,T,T];
type HomeCopy = {
  hero: [string, string, string, string, string, string];
  sections: Nine<[string, string]>;
  featureDescriptions: Twelve<string>;
  steps: Five<[string, string]>;
  faqs: Five<[string, string]>;
  realCaption: string;
  realAlt: [string, string, string, string];
};
export type Translation = {
  nav: [string, string, string, string, string, string, string];
  meta: Record<PublicPage, { title: string; description: string }>;
  home: HomeCopy;
  pages: Record<Exclude<PublicPage, ''>, PageCopy>;
  legalReview: string;
  readMore: string;
};

const featureNames = ['Order Flow','DOM and Trade Tape','Delta and CVD','Open Interest and Funding','Whale Activity','Iceberg and Absorption','Market Context','Historical Bootstrap','Scenario Outcome Lab','Dataset Recorder','Signal Journal','Diagnostics and Replay'];
export { featureNames };

const en: Translation = {
  nav: ['Features','How It Works','Scenario Lab','Screenshots','FAQ','Documentation','Closed Beta'],
  meta: {
    '': { title: 'DepthLume', description: 'See deeper into market behavior with explainable order flow, market context and scenario research.' },
    documentation: { title: 'Documentation', description: 'Pre-release product documentation and operating principles for DepthLume.' },
    'closed-beta': { title: 'Closed Beta', description: 'Learn about planned closed beta access for DepthLume.' },
    privacy: { title: 'Preliminary Privacy Notice', description: 'Preliminary privacy information for DepthLume.' },
    terms: { title: 'Preliminary Terms', description: 'Preliminary terms for DepthLume.' },
    'risk-disclaimer': { title: 'Preliminary Risk Disclaimer', description: 'Preliminary market-risk information for DepthLume.' },
  },
  home: {
    hero: ['Windows Desktop Market Intelligence','See deeper into market behavior.','DepthLume brings real-time order flow, market context and explainable scenario analysis into one professional Windows workspace.','Explore the Platform','Join Closed Beta','No trading-account connection required.'],
    sections: [['Market Understanding','Many signals. One explainable context.'],['Decision Engine','A conclusion you can interrogate.'],['Scenario Outcome Lab','Turn observations into accountable research.'],['Platform Capabilities','A complete research surface.'],['Product Interface','Real product detail, shown responsibly.'],['How DepthLume Works','From public data to your own decision.'],['Native Workstation','Designed for the Windows desktop.'],['Closed Beta','Help shape a more transparent market research workspace.'],['FAQ','Clear answers before access.']],
    featureDescriptions: ['Study executed activity beyond price.','Inspect liquidity and public trades.','Track aggressive flow imbalance.','Add derivatives positioning context.','Review unusually large activity.','Investigate defended price areas.','See evidence, conflicts and risk together.','Initialize context from historical data.','Observe and evaluate scenario outcomes.','Capture structured research datasets.','Review context records responsibly.','Inspect data health and deterministic replay.'],
    steps: [['Install DepthLume','Use the distributed Windows beta build.'],['Select a supported market','Choose a market confirmed for your build.'],['Receive public market data','Process real-time public data locally.'],['Evaluate the context','Review evidence, conflicts, risk and quality.'],['Make your own decision','Use research input, never an instruction.']],
    faqs: [['Does DepthLume execute trades?','No. It analyzes markets and never places or manages trades.'],['Is it a signal service?','No. Context labels are research states, not instructions or guarantees.'],['Does it require API keys?','No trading-account connection is required.'],['Which operating systems are supported?','DepthLume is a Windows desktop application.'],['Does DepthLume guarantee profitability?','No. Futures involve substantial risk and no analysis guarantees an outcome.']],
    realCaption: 'Real DepthLume development interface. Layout and displayed market data may change before release.',
    realAlt: ['Candlestick chart in the DepthLume development interface','LONG and SHORT Market Context status panel','Delta and CVD analysis panel','Liquidity heatmap analysis panel'],
  },
  pages: {
    documentation: { title:'DepthLume product guide',description:'Documentation',heading:'Product purpose and operating principles',lede:'A pre-release overview of the Windows market research workspace.',notice:'Interface details, supported sources and requirements remain subject to confirmation.',body:'DepthLume organizes public market data, order flow and explainable context. Review evidence, conflicts, risks, invalidation and data quality before making your own decision.' },
    'closed-beta': { title:'Closed Beta',description:'Product evaluation',heading:'Preparing for focused evaluation',lede:'The first beta prioritizes reliability, explainability and careful feedback.',notice:'Access timing, markets and system requirements are not final.',body:'Participants will evaluate context clarity, order-flow workflow, scenario review, diagnostics and Windows stability. A contact channel will be added after its privacy process is approved.' },
    privacy: { title:'Privacy notice',description:'Legal / Preliminary',heading:'Current privacy scope',lede:'This static prototype has no accounts, forms, payments or analytics.',notice:'Final legal review is required before public launch.',body:'Future registration, hosting or support services may process information and will require complete disclosures before activation.' },
    terms: { title:'Terms of use',description:'Legal / Preliminary',heading:'Informational purpose',lede:'DepthLume is market analytics software, not financial advice.',notice:'Final legal drafting and jurisdiction review are required before launch.',body:'DepthLume does not execute trades, manage funds or guarantee results. Availability and unfinished features remain subject to validation.' },
    'risk-disclaimer': { title:'Risk disclaimer',description:'Legal / Preliminary',heading:'Substantial risk of loss',lede:'Cryptocurrency futures are volatile and may cause rapid losses.',notice:'Final legal review is required before software distribution.',body:'Data may be delayed, incomplete or wrong. Context strength is not a probability of profit. Users independently assess risk and make their own decisions.' },
  }, legalReview:'Final legal review required before launch.', readMore:'Learn more',
};

const uk: Translation = {
  nav:['Можливості','Як це працює','Лабораторія сценаріїв','Знімки екрана','Питання','Документація','Закрита бета'],
  meta:{'':{title:'DepthLume',description:'Глибше розуміння поведінки ринку через пояснюваний Order Flow, контекст і сценарні дослідження.'},documentation:{title:'Документація',description:'Попередня документація та принципи роботи DepthLume.'},'closed-beta':{title:'Закрита бета',description:'Інформація про майбутній закритий бета-тест DepthLume.'},privacy:{title:'Попереднє повідомлення про приватність',description:'Попередня інформація про приватність DepthLume.'},terms:{title:'Попередні умови',description:'Попередні умови використання DepthLume.'},'risk-disclaimer':{title:'Попередження про ризики',description:'Попередня інформація про ринкові ризики DepthLume.'}},
  home:{hero:['Ринкова аналітика для Windows','Побачте поведінку ринку глибше.','DepthLume поєднує Order Flow у реальному часі, ринковий контекст і пояснюваний аналіз сценаріїв у професійному Windows-середовищі.','Оглянути платформу','Долучитися до бети','Підключення торгового рахунку не потрібне.'],sections:[['Розуміння ринку','Багато сигналів. Один пояснюваний контекст.'],['Механізм рішень','Висновок, який можна перевірити.'],['Scenario Outcome Lab','Перетворюйте спостереження на відповідальне дослідження.'],['Можливості платформи','Цілісне середовище для досліджень.'],['Інтерфейс продукту','Реальні деталі продукту — відповідально.'],['Як працює DepthLume','Від публічних даних до вашого рішення.'],['Робоча станція','Створено для Windows.'],['Закрита бета','Допоможіть створити прозоріший інструмент дослідження.'],['Питання','Чіткі відповіді до початку доступу.']],featureDescriptions:['Аналізуйте виконані угоди поза межами ціни.','Досліджуйте ліквідність і публічні угоди.','Відстежуйте дисбаланс агресивного потоку.','Додавайте контекст позиціонування деривативів.','Перевіряйте незвично великі дії.','Досліджуйте захищені цінові зони.','Бачте докази, конфлікти й ризики разом.','Ініціалізуйте контекст історичними даними.','Спостерігайте й оцінюйте результати сценаріїв.','Записуйте структуровані набори даних.','Переглядайте записи контексту відповідально.','Перевіряйте стан даних і відтворення.'],steps:[['Встановіть DepthLume','Використайте поширювану Windows-збірку.'],['Оберіть ринок','Оберіть підтверджений для збірки ринок.'],['Отримуйте публічні дані','Обробляйте дані локально в реальному часі.'],['Оцініть контекст','Перевірте докази, конфлікти, ризик і якість.'],['Прийміть власне рішення','Використовуйте дослідження, а не інструкцію.']],faqs:[['Чи виконує DepthLume угоди?','Ні. Програма аналізує ринок і не розміщує угод.'],['Це сервіс сигналів?','Ні. Позначки контексту не є наказами чи гарантіями.'],['Чи потрібні API-ключі?','Підключення торгового рахунку не потрібне.'],['Які ОС підтримуються?','DepthLume — настільна програма для Windows.'],['Чи гарантує DepthLume прибутковість?','Ні. Ф’ючерси мають значний ризик, а аналіз не гарантує результат.']],realCaption:'Реальний інтерфейс DepthLume у розробці. Компонування й показані ринкові дані можуть змінитися до релізу.',realAlt:['Свічковий графік в інтерфейсі DepthLume','Панель статусу LONG і SHORT Market Context','Панель аналізу Delta та CVD','Панель аналізу теплової карти ліквідності']},
  pages:{documentation:{title:'Посібник DepthLume',description:'Документація',heading:'Призначення і принципи роботи',lede:'Попередній огляд Windows-середовища ринкових досліджень.',notice:'Деталі інтерфейсу, джерела й вимоги ще уточнюються.',body:'DepthLume впорядковує публічні ринкові дані, Order Flow і пояснюваний контекст. Перед власним рішенням оцінюйте докази, конфлікти, ризики, інвалідацію та якість даних.'},'closed-beta':{title:'Закрита бета',description:'Оцінювання продукту',heading:'Підготовка до сфокусованого тестування',lede:'Перша бета зосереджена на надійності, пояснюваності й змістовному відгуку.',notice:'Строки, ринки й системні вимоги ще не остаточні.',body:'Учасники оцінюватимуть зрозумілість контексту, Order Flow, сценарії, діагностику та стабільність Windows-збірки.'},privacy:{title:'Повідомлення про приватність',description:'Правова інформація / Попередньо',heading:'Поточний обсяг приватності',lede:'Цей статичний прототип не має акаунтів, форм, платежів чи аналітики.',notice:'До запуску потрібна фінальна юридична перевірка.',body:'Майбутня реєстрація, хостинг або підтримка можуть обробляти дані й потребуватимуть повного розкриття до активації.'},terms:{title:'Умови використання',description:'Правова інформація / Попередньо',heading:'Інформаційне призначення',lede:'DepthLume — аналітичне ПЗ, а не фінансова порада.',notice:'До запуску потрібні юридичне доопрацювання та перевірка юрисдикції.',body:'DepthLume не виконує угод, не керує коштами й не гарантує результатів. Доступність функцій підлягає перевірці.'},'risk-disclaimer':{title:'Попередження про ризики',description:'Правова інформація / Попередньо',heading:'Значний ризик втрат',lede:'Криптовалютні ф’ючерси волатильні й можуть спричинити швидкі втрати.',notice:'До розповсюдження потрібна фінальна юридична перевірка.',body:'Дані можуть бути затриманими, неповними або помилковими. Сила контексту не є ймовірністю прибутку. Користувач сам оцінює ризик.'}},legalReview:'До запуску потрібна фінальна юридична перевірка.',readMore:'Докладніше'
};

const ru: Translation = {
  ...uk,
  nav:['Возможности','Как это работает','Лаборатория сценариев','Скриншоты','Вопросы','Документация','Закрытая бета'],
  meta:{'':{title:'DepthLume',description:'Глубже понимать рынок с объяснимым Order Flow, контекстом и сценарным исследованием.'},documentation:{title:'Документация',description:'Предварительная документация DepthLume.'},'closed-beta':{title:'Закрытая бета',description:'Информация о закрытом бета-тестировании DepthLume.'},privacy:{title:'Предварительное уведомление о конфиденциальности',description:'Предварительная информация о конфиденциальности.'},terms:{title:'Предварительные условия',description:'Предварительные условия DepthLume.'},'risk-disclaimer':{title:'Предупреждение о рисках',description:'Предварительная информация о рисках.'}},
  home:{...uk.home,hero:['Рыночная аналитика для Windows','Смотрите глубже в поведение рынка.','DepthLume объединяет Order Flow в реальном времени, рыночный контекст и объяснимый анализ сценариев в профессиональной Windows-среде.','Изучить платформу','Присоединиться к бете','Подключение торгового счёта не требуется.'],sections:[['Понимание рынка','Много сигналов. Один объяснимый контекст.'],['Механизм решений','Вывод, который можно проверить.'],['Scenario Outcome Lab','Превращайте наблюдения в ответственное исследование.'],['Возможности','Целостная среда исследований.'],['Интерфейс продукта','Реальные детали продукта — ответственно.'],['Как работает DepthLume','От публичных данных к вашему решению.'],['Рабочая станция','Создано для Windows.'],['Закрытая бета','Помогите создать более прозрачный инструмент.'],['Вопросы','Чёткие ответы до начала доступа.']],featureDescriptions:['Анализируйте исполненные сделки помимо цены.','Изучайте ликвидность и публичные сделки.','Отслеживайте дисбаланс агрессивного потока.','Добавляйте контекст деривативов.','Проверяйте необычно крупную активность.','Исследуйте защищённые ценовые зоны.','Смотрите доказательства, конфликты и риски вместе.','Инициализируйте контекст историческими данными.','Наблюдайте и оценивайте сценарии.','Записывайте структурированные данные.','Ответственно изучайте записи контекста.','Проверяйте данные и воспроизведение.'],steps:[['Установите DepthLume','Используйте Windows-сборку беты.'],['Выберите рынок','Выберите подтверждённый рынок.'],['Получайте публичные данные','Обрабатывайте данные локально.'],['Оцените контекст','Проверьте доказательства, конфликты, риск и качество.'],['Примите своё решение','Используйте исследование, а не инструкцию.']],faqs:[['DepthLume совершает сделки?','Нет. Программа анализирует рынок и не торгует.'],['Это сервис сигналов?','Нет. Метки контекста не являются инструкциями.'],['Нужны API-ключи?','Подключение торгового счёта не требуется.'],['Какие ОС поддерживаются?','DepthLume — Windows-приложение.'],['DepthLume гарантирует прибыль?','Нет. Фьючерсы несут значительный риск.']],realCaption:'Реальный интерфейс DepthLume в разработке. Компоновка и показанные рыночные данные могут измениться до выпуска.',realAlt:['Свечной график в интерфейсе DepthLume','Панель LONG и SHORT Market Context','Панель анализа Delta и CVD','Тепловая карта ликвидности']},
  pages:{documentation:{title:'Руководство DepthLume',description:'Документация',heading:'Назначение и принципы работы',lede:'Предварительный обзор Windows-среды рыночных исследований.',notice:'Интерфейс, источники и требования ещё уточняются.',body:'DepthLume организует публичные данные, Order Flow и объяснимый контекст. Оценивайте доказательства, противоречия, риски, инвалидацию и качество данных.'},'closed-beta':{title:'Закрытая бета',description:'Оценка продукта',heading:'Подготовка к сфокусированному тестированию',lede:'Первая бета сосредоточена на надёжности и объяснимости.',notice:'Сроки, рынки и требования ещё не окончательны.',body:'Участники оценят контекст, Order Flow, сценарии, диагностику и стабильность Windows-сборки.'},privacy:{title:'Уведомление о конфиденциальности',description:'Правовая информация / Предварительно',heading:'Текущий объём',lede:'В этом статическом прототипе нет аккаунтов, форм, платежей или аналитики.',notice:'До запуска требуется окончательная юридическая проверка.',body:'Будущая регистрация, хостинг или поддержка потребуют полного раскрытия обработки данных.'},terms:{title:'Условия использования',description:'Правовая информация / Предварительно',heading:'Информационное назначение',lede:'DepthLume — аналитическое ПО, а не финансовый совет.',notice:'До запуска необходима юридическая доработка.',body:'DepthLume не совершает сделки, не управляет средствами и не гарантирует результат.'},'risk-disclaimer':{title:'Предупреждение о рисках',description:'Правовая информация / Предварительно',heading:'Значительный риск потерь',lede:'Криптовалютные фьючерсы волатильны и могут привести к быстрым потерям.',notice:'До распространения требуется юридическая проверка.',body:'Данные могут быть задержаны, неполны или ошибочны. Сила контекста — не вероятность прибыли.'}},legalReview:'До запуска требуется окончательная юридическая проверка.',readMore:'Подробнее'
};

function latin(base: Translation, values: Partial<Translation>): Translation { return { ...base, ...values } as Translation; }

const es = latin(en,{
  nav:['Funciones','Cómo funciona','Laboratorio de escenarios','Capturas','Preguntas','Documentación','Beta cerrada'],
  meta:{'':{title:'DepthLume',description:'Comprende mejor el mercado con Order Flow, contexto explicable e investigación de escenarios.'},documentation:{title:'Documentación',description:'Documentación preliminar de DepthLume.'},'closed-beta':{title:'Beta cerrada',description:'Información sobre la beta cerrada de DepthLume.'},privacy:{title:'Aviso preliminar de privacidad',description:'Información preliminar de privacidad.'},terms:{title:'Términos preliminares',description:'Términos preliminares de DepthLume.'},'risk-disclaimer':{title:'Aviso preliminar de riesgos',description:'Información preliminar sobre riesgos.'}},
  home:{...en.home,hero:['Inteligencia de mercado para Windows','Mira más allá del comportamiento del mercado.','DepthLume reúne Order Flow en tiempo real, contexto de mercado y análisis explicable de escenarios en un entorno profesional para Windows.','Explorar la plataforma','Unirse a la beta','No requiere conexión con una cuenta de trading.'],sections:[['Comprensión del mercado','Muchas señales. Un contexto explicable.'],['Motor de decisión','Una conclusión que puedes examinar.'],['Scenario Outcome Lab','Convierte observaciones en investigación responsable.'],['Capacidades','Una superficie completa de investigación.'],['Interfaz del producto','Detalles reales mostrados con responsabilidad.'],['Cómo funciona','De los datos públicos a tu decisión.'],['Estación de trabajo','Diseñado para Windows.'],['Beta cerrada','Ayuda a crear una investigación más transparente.'],['Preguntas','Respuestas claras antes del acceso.']],featureDescriptions:['Analiza la actividad ejecutada más allá del precio.','Examina liquidez y operaciones públicas.','Sigue el desequilibrio del flujo agresivo.','Añade contexto de derivados.','Revisa actividad de tamaño inusual.','Investiga zonas de precio defendidas.','Reúne evidencia, conflictos y riesgo.','Inicializa contexto con datos históricos.','Observa y evalúa escenarios.','Registra conjuntos de investigación.','Revisa registros de contexto.','Comprueba datos y reproducción.'],steps:[['Instala DepthLume','Usa la versión beta para Windows.'],['Selecciona un mercado','Elige un mercado confirmado.'],['Recibe datos públicos','Procesa datos en tiempo real localmente.'],['Evalúa el contexto','Revisa evidencia, conflictos, riesgo y calidad.'],['Toma tu decisión','Usa investigación, no instrucciones.']],faqs:[['¿DepthLume ejecuta operaciones?','No. Analiza el mercado y no opera.'],['¿Es un servicio de señales?','No. Las etiquetas de contexto no son instrucciones.'],['¿Requiere claves API?','No requiere cuenta de trading.'],['¿Qué sistemas admite?','DepthLume es una aplicación Windows.'],['¿Garantiza rentabilidad?','No. Los futuros implican un riesgo considerable.']],realCaption:'Interfaz real de DepthLume en desarrollo. El diseño y los datos mostrados pueden cambiar antes del lanzamiento.',realAlt:['Gráfico de velas de DepthLume','Panel LONG y SHORT de Market Context','Panel Delta y CVD','Mapa de calor de liquidez']},
  pages:{documentation:{title:'Guía de DepthLume',description:'Documentación',heading:'Propósito y principios',lede:'Vista preliminar del espacio de investigación para Windows.',notice:'La interfaz, fuentes y requisitos están por confirmar.',body:'DepthLume organiza datos públicos, Order Flow y contexto explicable. Revisa evidencia, conflictos, riesgos, invalidación y calidad.'},'closed-beta':{title:'Beta cerrada',description:'Evaluación del producto',heading:'Preparación para una evaluación enfocada',lede:'La primera beta prioriza fiabilidad y claridad.',notice:'Fechas, mercados y requisitos no son definitivos.',body:'Los participantes evaluarán contexto, Order Flow, escenarios, diagnóstico y estabilidad.'},privacy:{title:'Aviso de privacidad',description:'Legal / Preliminar',heading:'Alcance actual',lede:'Este prototipo no tiene cuentas, formularios, pagos ni analítica.',notice:'Se requiere revisión legal antes del lanzamiento.',body:'Servicios futuros deberán explicar todo tratamiento de datos antes de activarse.'},terms:{title:'Términos de uso',description:'Legal / Preliminar',heading:'Finalidad informativa',lede:'DepthLume es software analítico, no asesoramiento financiero.',notice:'Se requiere redacción y revisión legal final.',body:'DepthLume no opera, no gestiona fondos ni garantiza resultados.'},'risk-disclaimer':{title:'Aviso de riesgos',description:'Legal / Preliminar',heading:'Riesgo considerable de pérdida',lede:'Los futuros de criptomonedas son volátiles.',notice:'Se requiere revisión legal antes de distribuir el software.',body:'Los datos pueden ser tardíos o erróneos. La fuerza del contexto no es probabilidad de beneficio.'}},legalReview:'Revisión legal final requerida antes del lanzamiento.',readMore:'Más información'
});

const pt = latin(es,{
  nav:['Recursos','Como funciona','Laboratório de cenários','Capturas','Perguntas','Documentação','Beta fechada'],
  meta:{'':{title:'DepthLume',description:'Entenda melhor o mercado com Order Flow, contexto explicável e pesquisa de cenários.'},documentation:{title:'Documentação',description:'Documentação preliminar do DepthLume.'},'closed-beta':{title:'Beta fechada',description:'Informações sobre a beta fechada.'},privacy:{title:'Aviso preliminar de privacidade',description:'Informações preliminares de privacidade.'},terms:{title:'Termos preliminares',description:'Termos preliminares do DepthLume.'},'risk-disclaimer':{title:'Aviso preliminar de riscos',description:'Informações preliminares de risco.'}},
  home:{...es.home,hero:['Inteligência de mercado para Windows','Veja mais fundo no comportamento do mercado.','DepthLume reúne Order Flow em tempo real, contexto de mercado e análise explicável de cenários em um ambiente profissional para Windows.','Explorar a plataforma','Participar da beta','Não requer conexão com conta de trading.'],sections:[['Compreensão do mercado','Muitos sinais. Um contexto explicável.'],['Mecanismo de decisão','Uma conclusão que você pode investigar.'],['Scenario Outcome Lab','Transforme observações em pesquisa responsável.'],['Recursos','Uma superfície completa de pesquisa.'],['Interface do produto','Detalhes reais mostrados com responsabilidade.'],['Como funciona','Dos dados públicos à sua decisão.'],['Estação de trabalho','Projetado para Windows.'],['Beta fechada','Ajude a criar uma pesquisa mais transparente.'],['Perguntas','Respostas claras antes do acesso.']],featureDescriptions:['Analise a atividade executada além do preço.','Examine liquidez e negócios públicos.','Acompanhe o desequilíbrio do fluxo agressivo.','Adicione contexto de derivativos.','Revise atividades de tamanho incomum.','Investigue zonas de preço defendidas.','Reúna evidências, conflitos e riscos.','Inicialize o contexto com dados históricos.','Observe e avalie cenários.','Registre dados estruturados de pesquisa.','Revise registros de contexto.','Verifique dados e reprodução.'],steps:[['Instale o DepthLume','Use a versão beta para Windows.'],['Selecione um mercado','Escolha um mercado confirmado.'],['Receba dados públicos','Processe dados em tempo real localmente.'],['Avalie o contexto','Revise evidências, conflitos, risco e qualidade.'],['Tome sua decisão','Use pesquisa, não instruções.']],faqs:[['O DepthLume executa operações?','Não. Ele analisa o mercado e não opera.'],['É um serviço de sinais?','Não. Rótulos de contexto não são instruções.'],['Exige chaves de API?','Não requer conexão com conta de trading.'],['Quais sistemas são suportados?','DepthLume é um aplicativo Windows.'],['Garante rentabilidade?','Não. Futuros envolvem risco substancial.']],realCaption:'Interface real do DepthLume em desenvolvimento. O layout e os dados exibidos podem mudar antes do lançamento.',realAlt:['Gráfico de candles no DepthLume','Painel LONG e SHORT do Market Context','Painel Delta e CVD','Mapa de calor de liquidez']},
  pages:{documentation:{title:'Guia do DepthLume',description:'Documentação',heading:'Objetivo e princípios',lede:'Visão preliminar do ambiente de pesquisa para Windows.',notice:'Interface, fontes e requisitos ainda serão confirmados.',body:'DepthLume organiza dados públicos, Order Flow e contexto explicável. Revise evidências, conflitos, riscos, invalidação e qualidade.'},'closed-beta':{title:'Beta fechada',description:'Avaliação do produto',heading:'Preparação para avaliação focada',lede:'A primeira beta prioriza confiabilidade e clareza.',notice:'Datas, mercados e requisitos não são definitivos.',body:'Participantes avaliarão contexto, Order Flow, cenários, diagnóstico e estabilidade.'},privacy:{title:'Aviso de privacidade',description:'Legal / Preliminar',heading:'Escopo atual',lede:'Este protótipo não possui contas, formulários, pagamentos ou analytics.',notice:'Revisão jurídica final é necessária antes do lançamento.',body:'Serviços futuros deverão informar todo tratamento de dados.'},terms:{title:'Termos de uso',description:'Legal / Preliminar',heading:'Finalidade informativa',lede:'DepthLume é software analítico, não consultoria financeira.',notice:'Redação e revisão jurídica final são necessárias.',body:'DepthLume não opera, não administra fundos nem garante resultados.'},'risk-disclaimer':{title:'Aviso de riscos',description:'Legal / Preliminar',heading:'Risco relevante de perda',lede:'Futuros de criptoativos são voláteis.',notice:'Revisão jurídica é necessária antes da distribuição.',body:'Dados podem atrasar ou estar errados. Força do contexto não é probabilidade de lucro.'}},legalReview:'Revisão jurídica final necessária antes do lançamento.',readMore:'Saiba mais'
});

const de = latin(en,{
  nav:['Funktionen','So funktioniert es','Szenario-Labor','Screenshots','FAQ','Dokumentation','Geschlossene Beta'],
  meta:{'':{title:'DepthLume',description:'Marktverhalten mit erklärbarem Order Flow, Kontext und Szenarioforschung tiefer verstehen.'},documentation:{title:'Dokumentation',description:'Vorläufige DepthLume-Dokumentation.'},'closed-beta':{title:'Geschlossene Beta',description:'Informationen zur geschlossenen Beta.'},privacy:{title:'Vorläufiger Datenschutzhinweis',description:'Vorläufige Datenschutzinformationen.'},terms:{title:'Vorläufige Bedingungen',description:'Vorläufige Nutzungsbedingungen.'},'risk-disclaimer':{title:'Vorläufiger Risikohinweis',description:'Vorläufige Markt-Risikoinformationen.'}},
  home:{...en.home,hero:['Marktintelligenz für Windows','Marktverhalten tiefer erkennen.','DepthLume vereint Order Flow in Echtzeit, Marktkontext und erklärbare Szenarioanalyse in einer professionellen Windows-Arbeitsumgebung.','Plattform erkunden','An Beta teilnehmen','Keine Verbindung zu einem Handelskonto erforderlich.'],sections:[['Marktverständnis','Viele Signale. Ein erklärbarer Kontext.'],['Entscheidungslogik','Eine Schlussfolgerung, die prüfbar bleibt.'],['Scenario Outcome Lab','Beobachtungen in nachvollziehbare Forschung verwandeln.'],['Funktionen','Eine vollständige Forschungsoberfläche.'],['Produktoberfläche','Echte Details verantwortungsvoll gezeigt.'],['So funktioniert es','Von öffentlichen Daten zu Ihrer Entscheidung.'],['Arbeitsstation','Für Windows entwickelt.'],['Geschlossene Beta','Gestalten Sie transparentere Marktforschung mit.'],['FAQ','Klare Antworten vor dem Zugang.']],featureDescriptions:['Ausgeführte Aktivität jenseits des Preises.','Liquidität und öffentliche Trades prüfen.','Aggressives Flussungleichgewicht verfolgen.','Derivatepositionierung einordnen.','Ungewöhnlich große Aktivität prüfen.','Verteidigte Preiszonen untersuchen.','Evidenz, Konflikte und Risiken bündeln.','Kontext mit Historie initialisieren.','Szenarien beobachten und bewerten.','Strukturierte Forschungsdaten erfassen.','Kontextaufzeichnungen prüfen.','Datenzustand und Replay untersuchen.'],steps:[['DepthLume installieren','Die Windows-Betaversion verwenden.'],['Markt auswählen','Einen bestätigten Markt wählen.'],['Öffentliche Daten empfangen','Echtzeitdaten lokal verarbeiten.'],['Kontext bewerten','Evidenz, Konflikte, Risiko und Qualität prüfen.'],['Selbst entscheiden','Forschung nutzen, keine Anweisung.']],faqs:[['Führt DepthLume Trades aus?','Nein. Es analysiert und handelt nicht.'],['Ist es ein Signaldienst?','Nein. Kontextlabels sind keine Anweisungen.'],['Sind API-Schlüssel nötig?','Keine Handelskontoverbindung ist nötig.'],['Welche Systeme werden unterstützt?','DepthLume ist eine Windows-Desktop-App.'],['Garantiert DepthLume Gewinne?','Nein. Futures bergen erhebliche Risiken.']],realCaption:'Echte DepthLume-Entwicklungsoberfläche. Layout und gezeigte Marktdaten können sich vor Veröffentlichung ändern.',realAlt:['Kerzenchart in DepthLume','LONG/SHORT-Market-Context-Panel','Delta- und CVD-Panel','Liquiditäts-Heatmap']},
  pages:{documentation:{title:'DepthLume-Leitfaden',description:'Dokumentation',heading:'Zweck und Prinzipien',lede:'Vorläufiger Überblick der Windows-Forschungsumgebung.',notice:'Oberfläche, Quellen und Anforderungen werden noch bestätigt.',body:'DepthLume ordnet öffentliche Daten, Order Flow und erklärbaren Kontext. Prüfen Sie Evidenz, Konflikte, Risiken, Invalidierung und Qualität.'},'closed-beta':{title:'Geschlossene Beta',description:'Produktbewertung',heading:'Vorbereitung auf gezielte Evaluation',lede:'Die erste Beta priorisiert Zuverlässigkeit und Erklärbarkeit.',notice:'Termine, Märkte und Anforderungen sind nicht final.',body:'Teilnehmende bewerten Kontext, Order Flow, Szenarien, Diagnose und Stabilität.'},privacy:{title:'Datenschutzhinweis',description:'Rechtliches / Vorläufig',heading:'Aktueller Umfang',lede:'Dieser Prototyp hat keine Konten, Formulare, Zahlungen oder Analytics.',notice:'Vor dem Start ist eine Rechtsprüfung erforderlich.',body:'Künftige Dienste müssen jede Datenverarbeitung vor Aktivierung offenlegen.'},terms:{title:'Nutzungsbedingungen',description:'Rechtliches / Vorläufig',heading:'Informationszweck',lede:'DepthLume ist Analysesoftware, keine Finanzberatung.',notice:'Finale rechtliche Ausarbeitung ist erforderlich.',body:'DepthLume handelt nicht, verwaltet keine Gelder und garantiert keine Ergebnisse.'},'risk-disclaimer':{title:'Risikohinweis',description:'Rechtliches / Vorläufig',heading:'Erhebliches Verlustrisiko',lede:'Krypto-Futures sind volatil.',notice:'Vor Vertrieb ist eine Rechtsprüfung erforderlich.',body:'Daten können verspätet oder falsch sein. Kontextstärke ist keine Gewinnwahrscheinlichkeit.'}},legalReview:'Finale Rechtsprüfung vor Veröffentlichung erforderlich.',readMore:'Mehr erfahren'
});

const tr = latin(en,{
  nav:['Özellikler','Nasıl çalışır','Senaryo Laboratuvarı','Ekran görüntüleri','SSS','Belgeler','Kapalı Beta'],
  meta:{'':{title:'DepthLume',description:'Açıklanabilir Order Flow, piyasa bağlamı ve senaryo araştırmasıyla piyasayı daha derin görün.'},documentation:{title:'Belgeler',description:'DepthLume ön sürüm belgeleri.'},'closed-beta':{title:'Kapalı Beta',description:'DepthLume kapalı beta bilgileri.'},privacy:{title:'Ön Gizlilik Bildirimi',description:'Ön gizlilik bilgileri.'},terms:{title:'Ön Koşullar',description:'DepthLume ön kullanım koşulları.'},'risk-disclaimer':{title:'Ön Risk Uyarısı',description:'Ön piyasa riski bilgileri.'}},
  home:{...en.home,hero:['Windows Masaüstü Piyasa Zekâsı','Piyasa davranışını daha derin görün.','DepthLume gerçek zamanlı Order Flow, piyasa bağlamı ve açıklanabilir senaryo analizini profesyonel bir Windows çalışma alanında birleştirir.','Platformu keşfet','Betaya katıl','İşlem hesabı bağlantısı gerekmez.'],sections:[['Piyasa anlayışı','Çok sayıda veri. Tek açıklanabilir bağlam.'],['Karar motoru','Sorgulayabileceğiniz bir sonuç.'],['Scenario Outcome Lab','Gözlemleri sorumlu araştırmaya dönüştürün.'],['Özellikler','Eksiksiz bir araştırma yüzeyi.'],['Ürün arayüzü','Gerçek ürün ayrıntıları, sorumlu sunum.'],['Nasıl çalışır','Herkese açık veriden kendi kararınıza.'],['İş istasyonu','Windows için tasarlandı.'],['Kapalı Beta','Daha şeffaf araştırmayı birlikte şekillendirin.'],['SSS','Erişim öncesi net yanıtlar.']],featureDescriptions:['Fiyatın ötesindeki işlemleri inceleyin.','Likidite ve işlemleri izleyin.','Agresif akış dengesizliğini takip edin.','Türev konumlanmasını bağlama ekleyin.','Olağandışı büyük etkinliği inceleyin.','Savunulan fiyat bölgelerini araştırın.','Kanıt, çelişki ve riski birlikte görün.','Geçmiş verilerle bağlam başlatın.','Senaryoları gözleyip değerlendirin.','Yapılandırılmış veri kaydedin.','Bağlam kayıtlarını inceleyin.','Veri sağlığı ve replay’i denetleyin.'],steps:[['DepthLume’u kurun','Windows beta sürümünü kullanın.'],['Piyasa seçin','Onaylanmış bir piyasa seçin.'],['Herkese açık veri alın','Gerçek zamanlı veriyi yerel işleyin.'],['Bağlamı değerlendirin','Kanıt, çelişki, risk ve kaliteyi inceleyin.'],['Kendi kararınızı verin','Araştırmayı kullanın, talimatı değil.']],faqs:[['DepthLume işlem yapar mı?','Hayır. Piyasayı analiz eder, işlem yapmaz.'],['Sinyal servisi mi?','Hayır. Bağlam etiketleri talimat değildir.'],['API anahtarı gerekir mi?','İşlem hesabı bağlantısı gerekmez.'],['Hangi sistemler desteklenir?','DepthLume bir Windows masaüstü uygulamasıdır.'],['Kârı garanti eder mi?','Hayır. Vadeli işlemler ciddi risk taşır.']],realCaption:'Gerçek DepthLume geliştirme arayüzü. Düzen ve gösterilen piyasa verileri sürümden önce değişebilir.',realAlt:['DepthLume mum grafiği','LONG ve SHORT Market Context paneli','Delta ve CVD paneli','Likidite ısı haritası']},
  pages:{documentation:{title:'DepthLume rehberi',description:'Belgeler',heading:'Amaç ve ilkeler',lede:'Windows araştırma ortamına ön bakış.',notice:'Arayüz, kaynaklar ve gereksinimler henüz kesin değildir.',body:'DepthLume herkese açık veriyi, Order Flow’u ve açıklanabilir bağlamı düzenler. Kanıt, çelişki, risk, geçersiz kılma ve kaliteyi inceleyin.'},'closed-beta':{title:'Kapalı Beta',description:'Ürün değerlendirmesi',heading:'Odaklı değerlendirmeye hazırlık',lede:'İlk beta güvenilirlik ve açıklanabilirliği önceler.',notice:'Tarih, piyasa ve gereksinimler kesin değildir.',body:'Katılımcılar bağlamı, Order Flow’u, senaryoları, tanılamayı ve kararlılığı değerlendirecek.'},privacy:{title:'Gizlilik bildirimi',description:'Hukuki / Ön',heading:'Mevcut kapsam',lede:'Bu prototipte hesap, form, ödeme veya analitik yoktur.',notice:'Yayın öncesi hukuki inceleme gerekir.',body:'Gelecekteki hizmetler veri işlemeyi etkinleşmeden açıklamalıdır.'},terms:{title:'Kullanım koşulları',description:'Hukuki / Ön',heading:'Bilgilendirme amacı',lede:'DepthLume analiz yazılımıdır; finansal tavsiye değildir.',notice:'Nihai hukuki metin gerekir.',body:'DepthLume işlem yapmaz, fon yönetmez ve sonuç garantilemez.'},'risk-disclaimer':{title:'Risk uyarısı',description:'Hukuki / Ön',heading:'Önemli kayıp riski',lede:'Kripto vadeli işlemleri oynaktır.',notice:'Dağıtım öncesi hukuki inceleme gerekir.',body:'Veri gecikebilir veya yanlış olabilir. Bağlam gücü kâr olasılığı değildir.'}},legalReview:'Yayın öncesi nihai hukuki inceleme gerekir.',readMore:'Daha fazla bilgi'
});

const zh = latin(en,{
  nav:['功能','工作方式','情景实验室','界面截图','常见问题','文档','封闭测试'],
  meta:{'':{title:'DepthLume',description:'通过可解释的 Order Flow、市场背景和情景研究，更深入地理解市场行为。'},documentation:{title:'文档',description:'DepthLume 预发布产品文档。'},'closed-beta':{title:'封闭测试',description:'DepthLume 封闭测试信息。'},privacy:{title:'初步隐私声明',description:'DepthLume 初步隐私信息。'},terms:{title:'初步条款',description:'DepthLume 初步使用条款。'},'risk-disclaimer':{title:'初步风险提示',description:'DepthLume 初步市场风险信息。'}},
  home:{...en.home,hero:['Windows 桌面市场智能','更深入地洞察市场行为。','DepthLume 将实时 Order Flow、市场背景和可解释的情景分析整合在一个专业的 Windows 工作区中。','探索平台','加入封闭测试','无需连接交易账户。'],sections:[['市场理解','多种信号，一个可解释的背景。'],['决策引擎','可以审查的结论。'],['Scenario Outcome Lab','将观察转化为负责任的研究。'],['平台功能','完整的研究界面。'],['产品界面','负责任地展示真实产品细节。'],['工作方式','从公开数据到您自己的决定。'],['本地工作站','专为 Windows 设计。'],['封闭测试','共同打造更透明的市场研究工具。'],['常见问题','开放访问前的明确答案。']],featureDescriptions:['分析价格之外的已执行活动。','查看流动性与公开成交。','追踪主动交易流失衡。','加入衍生品持仓背景。','审查异常大额活动。','研究被防守的价格区域。','同时查看证据、冲突与风险。','用历史数据初始化背景。','观察并评估情景结果。','记录结构化研究数据。','审慎回顾背景记录。','检查数据健康与确定性回放。'],steps:[['安装 DepthLume','使用发布的 Windows 测试版本。'],['选择市场','选择当前版本确认支持的市场。'],['接收公开数据','在本地处理实时公开数据。'],['评估背景','审查证据、冲突、风险和质量。'],['自行决策','将其作为研究输入，而非指令。']],faqs:[['DepthLume 会执行交易吗？','不会。它分析市场，但不下单或管理交易。'],['它是交易信号服务吗？','不是。背景标签不是指令或保证。'],['需要 API 密钥吗？','无需连接交易账户。'],['支持哪些系统？','DepthLume 是 Windows 桌面应用。'],['能保证盈利吗？','不能。期货具有重大风险，分析无法保证结果。']],realCaption:'真实的 DepthLume 开发界面。布局和所示市场数据在发布前可能变化。',realAlt:['DepthLume 开发界面的蜡烛图','LONG 与 SHORT Market Context 状态面板','Delta 与 CVD 分析面板','流动性热力图分析面板']},
  pages:{documentation:{title:'DepthLume 产品指南',description:'文档',heading:'产品目的与原则',lede:'Windows 市场研究工作区的预发布概览。',notice:'界面细节、数据源和系统要求仍待确认。',body:'DepthLume 整理公开市场数据、Order Flow 和可解释背景。请在自行决策前审查证据、冲突、风险、失效条件和数据质量。'},'closed-beta':{title:'封闭测试',description:'产品评估',heading:'准备专注的产品评估',lede:'首轮测试优先关注可靠性、可解释性和有效反馈。',notice:'时间、市场和系统要求尚未最终确定。',body:'参与者将评估市场背景、Order Flow 工作流、情景复盘、诊断和 Windows 稳定性。'},privacy:{title:'隐私声明',description:'法律 / 初步',heading:'当前隐私范围',lede:'此静态原型不包含账户、表单、支付或分析工具。',notice:'公开发布前必须完成最终法律审查。',body:'未来的注册、托管或支持服务在启用前必须完整说明数据处理。'},terms:{title:'使用条款',description:'法律 / 初步',heading:'信息用途',lede:'DepthLume 是市场分析软件，不构成金融建议。',notice:'发布前需要最终法律起草与审查。',body:'DepthLume 不执行交易、不管理资金，也不保证任何结果。'},'risk-disclaimer':{title:'风险提示',description:'法律 / 初步',heading:'重大损失风险',lede:'加密货币期货波动剧烈，可能迅速造成损失。',notice:'软件分发前必须完成最终法律审查。',body:'数据可能延迟、不完整或错误。背景强度不是盈利概率。用户须独立评估风险并自行决策。'}},legalReview:'发布前必须完成最终法律审查。',readMore:'了解更多'
});

export const translations = { en, uk, ru, es, 'pt-BR': pt, de, tr, 'zh-CN': zh } satisfies Record<Locale, Translation>;
export function getTranslation(locale: Locale): Translation { return translations[locale]; }
